# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_systemsreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True)),
                ('companion', models.CharField(max_length=50, null=True)),
                ('referred_by', models.CharField(max_length=50, null=True)),
                ('reason_consultation', models.TextField()),
                ('current_illness', models.TextField(null=True)),
                ('medical_formula', models.TextField(null=True)),
                ('paraclinics', models.TextField(null=True)),
                ('remission', models.TextField(null=True)),
                ('clinical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.ClinicalHistory')),
                ('patiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patiente')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.TextField(null=True)),
                ('mental_sphere', models.TextField(null=True)),
                ('head', models.TextField(null=True)),
                ('orl', models.TextField(null=True)),
                ('neck_thyroid', models.TextField(null=True)),
                ('chest', models.TextField(null=True)),
                ('cardiovascular', models.TextField(null=True)),
                ('respiratory', models.TextField(null=True)),
                ('digestive', models.TextField(null=True)),
                ('mammary_gland', models.TextField(null=True)),
                ('genitourinary', models.TextField(null=True)),
                ('snc_peripheral', models.TextField(null=True)),
                ('osteomuscular', models.TextField(null=True)),
                ('skin_faneras', models.TextField(null=True)),
                ('senses_organs', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='physical_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PhysicalExam'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='systems_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.SystemsReview'),
        ),
    ]
