# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20180213_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paraclinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ParaclinicalMedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='medical_formula',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='paraclinics',
        ),
        migrations.AddField(
            model_name='paraclinicalmedicalhistory',
            name='medical_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.MedicalHistory'),
        ),
        migrations.AddField(
            model_name='paraclinicalmedicalhistory',
            name='paraclinical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Paraclinical'),
        ),
        migrations.AddField(
            model_name='medicalformula',
            name='medical_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.MedicalHistory'),
        ),
        migrations.AddField(
            model_name='medicalformula',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Medicine'),
        ),
    ]
