# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20180216_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='allergic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='immunological',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='liqueur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='obstetric',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='pathological',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='permanent_medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='poisoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='psychoactive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='relatives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='smoking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='surgical',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='transfusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='traumatic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='companion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='current_illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='referred_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='remission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='is_generic',
            field=models.BooleanField(verbose_name='Gen\xe9rico'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Laboratory', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paraclinical',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='document',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.DocumentType', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Gender', verbose_name='G\xe9nero'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='cardiovascular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='chest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='digestive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='genitourinary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='head',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='mammary_gland',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='mental_sphere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='neck_thyroid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='orl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='osteomuscular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='respiratory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='senses_organs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='skin_faneras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='snc_peripheral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='weight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='cardiovascular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='digestive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='endocrine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='genitourinary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='hematic_lymphatic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='locomotor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='orl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='respiratory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='senses_organs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='skin_faneras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='snc_peripheral',
            field=models.TextField(blank=True, null=True),
        ),
    ]
