# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20180217_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='clinical_history',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patients.ClinicalHistory'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='physical_exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patients.PhysicalExam'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='systems_review',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patients.SystemsReview'),
        ),
    ]
