# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20180221_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalhistory',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='paraclinical',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['pk']},
        ),
    ]
