# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20180301_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='allergic',
            field=models.TextField(blank=True, null=True, verbose_name='Al\xe9rgicos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='immunological',
            field=models.TextField(blank=True, null=True, verbose_name='Inmunol\xf3gicos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='liqueur',
            field=models.TextField(blank=True, null=True, verbose_name='Licor'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='obstetric',
            field=models.TextField(blank=True, null=True, verbose_name='Obst\xe9tricos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='pathological',
            field=models.TextField(blank=True, null=True, verbose_name='Patol\xf3gicos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='permanent_medication',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamentos permanentes'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='poisoning',
            field=models.TextField(blank=True, null=True, verbose_name='Intoxicaciones'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='psychoactive',
            field=models.TextField(blank=True, null=True, verbose_name='Psicoactivos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='relatives',
            field=models.TextField(blank=True, null=True, verbose_name='Familiares'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='smoking',
            field=models.TextField(blank=True, null=True, verbose_name='Tabaquismo'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='surgical',
            field=models.TextField(blank=True, null=True, verbose_name='Quir\xfargicos'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='transfusions',
            field=models.TextField(blank=True, null=True, verbose_name='Transfusiones'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='traumatic',
            field=models.TextField(blank=True, null=True, verbose_name='Traum\xe1ticos'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='companion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Acompa\xf1ante'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='current_illness',
            field=models.TextField(blank=True, null=True, verbose_name='Enfermedad actual'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='reason_consultation',
            field=models.TextField(verbose_name='Raz\xf3n de consulta'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='referred_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referido por'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='remission',
            field=models.TextField(blank=True, null=True, verbose_name='Remisi\xf3n'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='cardiovascular',
            field=models.TextField(blank=True, null=True, verbose_name='Cardiovascular'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='chest',
            field=models.TextField(blank=True, null=True, verbose_name='T\xf3rax'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='digestive',
            field=models.TextField(blank=True, null=True, verbose_name='Digestivo'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='genitourinary',
            field=models.TextField(blank=True, null=True, verbose_name='Genito-urinario'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='head',
            field=models.TextField(blank=True, null=True, verbose_name='Cabeza'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='mammary_gland',
            field=models.TextField(blank=True, null=True, verbose_name='Mamas'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='mental_sphere',
            field=models.TextField(blank=True, null=True, verbose_name='Esfera mental'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='neck_thyroid',
            field=models.TextField(blank=True, null=True, verbose_name='Cuello - Tiroides'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='orl',
            field=models.TextField(blank=True, null=True, verbose_name='O.R.L'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='osteomuscular',
            field=models.TextField(blank=True, null=True, verbose_name='Osteomuscular'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='respiratory',
            field=models.TextField(blank=True, null=True, verbose_name='Respiratorio'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='senses_organs',
            field=models.TextField(blank=True, null=True, verbose_name='Organos de los sentidos'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='skin_faneras',
            field=models.TextField(blank=True, null=True, verbose_name='Piel y Faneras'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='snc_peripheral',
            field=models.TextField(blank=True, null=True, verbose_name='SNC y Periferico'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='weight',
            field=models.TextField(blank=True, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='cardiovascular',
            field=models.TextField(blank=True, null=True, verbose_name='Cardio-vascular'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='digestive',
            field=models.TextField(blank=True, null=True, verbose_name='Digestivo'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='endocrine',
            field=models.TextField(blank=True, null=True, verbose_name='Endocrino'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='genitourinary',
            field=models.TextField(blank=True, null=True, verbose_name='Genito-urinario'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='hematic_lymphatic',
            field=models.TextField(blank=True, null=True, verbose_name='Hem\xe1tico y Linf\xe1tico'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='locomotor',
            field=models.TextField(blank=True, null=True, verbose_name='Locomotor'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='orl',
            field=models.TextField(blank=True, null=True, verbose_name='O.R.L'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='respiratory',
            field=models.TextField(blank=True, null=True, verbose_name='Respiratorio'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='senses_organs',
            field=models.TextField(blank=True, null=True, verbose_name='Organos de los Sentidos'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='skin_faneras',
            field=models.TextField(blank=True, null=True, verbose_name='Piel y Faneras'),
        ),
        migrations.AlterField(
            model_name='systemsreview',
            name='snc_peripheral',
            field=models.TextField(blank=True, null=True, verbose_name='SNC y Periferico'),
        ),
    ]
