# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20180302_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='medicines',
            field=models.ManyToManyField(to='patients.Medicine'),
        ),
    ]
