# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 01:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_medicalhistory_paraclinicals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='A',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='A'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='C',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='C'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='Cic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cic'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='FUM',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FUM'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='FUP',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FUP'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='G',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='G'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='Menop',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Menop'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='P',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='P'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='men',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Men'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='created_day',
            field=models.IntegerField(default=7, verbose_name='D\xeda'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='created_hour',
            field=models.TimeField(default=datetime.time(1, 22, 45, 893357), verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='created_month',
            field=models.IntegerField(default=3, verbose_name='Mes'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='created_year',
            field=models.IntegerField(default=2018, verbose_name='A\xf1o'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='phone_companion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel\xe9fono del acompa\xf1ante'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='sgss',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referido SGSS'),
        ),
        migrations.AddField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Profesi\xf3n/ocupaci\xf3n'),
        ),
        migrations.AddField(
            model_name='patient',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Procedencia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profesion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Profesi\xf3n/ocupaci\xf3n'),
        ),
        migrations.AddField(
            model_name='patient',
            name='scholarship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel de escolaridad'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='Fc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fc'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='IM',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='I.M'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='TA',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TA'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='minfr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='/min.Fr'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='mint',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='/min.T'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='so',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SO2'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='tall',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tall'),
        ),
    ]
