# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_auto_20180308_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='created_day',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='created_hour',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='created_month',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='created_year',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='created_at_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='created_at_hour',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
        ),
    ]
