# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20180309_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalformula',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='medicalformula',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='paraclinicalmedicalhistory',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='paraclinicalmedicalhistory',
            name='paraclinical',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='city',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_city',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Ciudad de Nacimiento'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='diagnostics_images',
            field=models.TextField(blank=True, null=True, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='MedicalFormula',
        ),
        migrations.DeleteModel(
            name='ParaclinicalMedicalHistory',
        ),
    ]
