# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_auto_20180311_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='is_generic',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='laboratory',
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
    ]
