# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_auto_20180311_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalformulas',
            name='medicines',
            field=models.ManyToManyField(blank=True, to='patients.Medicine', verbose_name='Medicamentos'),
        ),
        migrations.AlterField(
            model_name='medicalformulas',
            name='paraclinicals',
            field=models.ManyToManyField(blank=True, to='patients.Paraclinical', verbose_name='Paracl\xednicos'),
        ),
    ]
