# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_auto_20180317_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalexam',
            name='pa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PA'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='pe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PE'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='sgss',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SGSS'),
        ),
    ]
