# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20180317_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIE10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='C\xf3digo')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='pe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PC'),
        ),
    ]
