# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_auto_20180317_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cie10',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
    ]
