# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_auto_20180318_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cie10',
            name='code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='C\xf3digo'),
        ),
    ]
