# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_auto_20180318_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalexam',
            name='diagnostics_images',
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='diagnostics_images',
            field=models.ManyToManyField(blank=True, to='patients.CIE10', verbose_name='Diagn\xf3stico'),
        ),
    ]
